services:
  db:
    container_name: capychef-db
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  email:
    container_name: email
    image: rnwood/smtp4dev:latest 
    ports:
      - "4080:80"
      - "2525:25"

volumes:
  db_data:
